### ISSUE TITLE
Scraping paused during sleep

### ISSUE THREAD

**Issue by mitchellcouchman** [knulli-cfw/distribution#18]
### Knulli build version

40-dev-905b0c4ff1 2024/03/01 04:16

### Your architecture

RG35XX H

### Issue description

Not sure if it's a bug or by design, but when the device goes into sleep, scraping pauses. Then scraping resumes when back out of sleep. Would be great if it could keep scraping during sleep so I didn't have to keep the screen on the entire time. Thanks!

### Detailed reproduction steps

1. Start scraping from Settings menu
2. Return to home screen
3. Watch scraping info top right corner, ensure it is processing through games.
4. Wait for scraping to change to new title
5. Quick press power button to sleep
6. Leave 5 minutes
7. Quick press power button to resume from sleep
8. Scraping info t op right shows same game it was processing 5 minutes ago
9. Moves to next game very quickly once out of sleep
10. Assumption is that scraping is paused while device is asleep. 

### Details of any modifications you have made to Knulli.

N/A

**Comment by HoroTW** [comment]
Hey, sorry for the very late reply.
This is by design and there is nothing we can really do about it, in sleep (standby) mode the device is unable to do anything.

But you can archive what you want by doing the following
- disable the automatic sleep mode (and of course don't put the device to sleep manually :wink:)
- with the hotkeys (F + -) you can adjust the screen brightness, if you click enough times the screen will turn off (but the device is not sleeping, just the screen is off)
- with (F + +) you can increase the screen brightness again, so you can see the screen again 

That should do the job 😊
