### ISSUE TITLE
Dreamcast on Trimui smart pro not working

### ISSUE THREAD

**Issue by akoufou** [knulli-cfw/distribution#57]
### Knulli build version

40-dev-f7e205a8b9 2024/05/16 12:53

### Your architecture

Trimui smart pro 

### Issue description

Dreamcast games don't start and go back to game selection screen. This happens with all 3 available emulators.
Bios files are present in root bios folder. 

### Detailed reproduction steps

Knulki is in a fresh installation and games are in both chd and folder forms. 

### Details of any attempts to fix this yourself

Tried changing emulator. no results.
However on my rg35xx h Dreamcast works flawlessly

### Details of any modifications you have made to Knulli.

none.

**Comment by graemetait** [comment]
I managed to track down that Flycast fails to start because 'mangohud' is missing, and the `emulatorlauncher` script tries to run that first. When mangohud can't be started the whole thing fails.

If you comment out this line, and the if statement above it (lines 279-280), then Flycast will launch fine.
https://github.com/knulli-cfw/distribution/blob/f2315a926f7b498cb7db0911907cc511af3d2039/package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py#L280

Unfortunately I'm finding so far that performance is not as good as on Stock or Crossmix.

**Comment by Ch3ck3rM0n** [comment]
> I managed to track down that Flycast fails to start because 'mangohud' is missing, and the `emulatorlauncher` script tries to run that first. When mangohud can't be started the whole thing fails.
> 
> If you comment out this line, and the if statement above it (lines 279-280), then Flycast will launch fine.
> 
> [distribution/package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py](https://github.com/knulli-cfw/distribution/blob/f2315a926f7b498cb7db0911907cc511af3d2039/package/batocera/core/batocera-configgen/configgen/configgen/emulatorlauncher.py#L280)
> 
> Line 280 in [f2315a9](/knulli-cfw/distribution/commit/f2315a926f7b498cb7db0911907cc511af3d2039)
> 
>  cmd.array.insert(0, "mangohud") 
> Unfortunately I'm finding so far that performance is not as good as on Stock or Crossmix.

hi man, I am not so deep right now but I have the some issue to my RG40XX-H..
do I have to recompile or can I just chang a file in the installed system?

**Comment by mtoensing** [comment]
Is there a way in Knulli for trim ui to make it work by altering settings?
