### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by bladeoner** [knulli-cfw/distribution#75]
### Knulli build version

40-dev-4b893c35df 2024/07/11 08:29

### Your architecture

RG35XX H

### Issue description

I have tried to compile the latest source, but it shows an error. The images are created and can be flashed, but the database sources under scraper seem to be missing.

![IMG-20240711-WA0010~2](https://github.com/knulli-cfw/distribution/assets/24655170/4abb8153-3a11-4259-8f45-5e6a1d374036)

### Detailed reproduction steps

I have performed the following steps:
- I have downloaded the following source code: https://github.com/knulli-cfw/distribution/commit/6829471be66e2c12ef60a958471b3f70bf67dca4
- I followed all the steps of the Batocera documentation to set up my device: https://wiki.batocera.org/compile_batocera.linux
- I used the following command to start the compile: make h700-build

### Details of any attempts to fix this yourself

Tried to compile twice,  first time with the mentioned source code. The second time with the mentioned source code, but I updated the batocera-emulationstation package to the latest version, both attempts the same results and error.

### Details of any modifications you have made to Knulli.

I just downloaded the source and started to compile it in a docker container.

### Logs and data

python /build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py /build/package/batocera/emulationstation/batocera-es-system/es_systems.yml /build/package/batocera/emulationstation/batocera-es-system/systems-explanations.yml /build/package/batocera/core/batocera-configgen/configs /tmp/br_systemreport_3516111/configs
Traceback (most recent call last):
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 218, in <module>
    EsSystemConf.generate(args.yml, args.explanationsYaml, args.configsDir, args.defaultsDir)
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 80, in generate
    emulators = EsSystemConf.listEmulators(arch, system, rules[system], explanations, config, defaultEmulator, defaultCore)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 182, in listEmulators
    raise Exception("default core ({}/{}) not enabled for {}/{}" . format(defaultEmulator, defaultCore, arch, system))
Exception: default core (libretro/flycast) not enabled for h3/systemsp
'+' exit 1
make: *** [Makefile:821: target-post-image] Error 1
make: Leaving directory '/build/buildroot'
make: *** [Makefile:104: h700-build] Error 2

**Comment by bladeoner** [comment]
I think I found the anwser, I will close the issue.

**Comment by jbbandos** [comment]
@bladeoner Would you mind sharing the answer? I am having the same issue.

**Comment by bladeoner** [comment]
Hi @jbbandos , I didn't manage to fix this error because the compiling is working. I didn't look into it anymore.

I think it's also not easy to fix.

**Comment by jbbandos** [comment]
@bladeoner But you now have compilation working? Because for me it stops here, after generating only the rg28xx image. I am unable to finish building the other images, as it always ends the same way:
`+ cp /h700/target/usr/share/batocera/batocera.version /h700/images/knulli
+ /build/scripts/linux/systemsReport.sh /build/buildroot /h700/images/knulli
generating .config for x86_64
generating .config for odroidxu4
generating .config for bcm2835
generating .config for bcm2836
generating .config for bcm2837
generating .config for bcm2711
generating .config for bcm2712
generating .config for rk3128
generating .config for rk3288
generating .config for rk3326
generating .config for rk3328
generating .config for rk3399
generating .config for rk3568
generating .config for rk3588
generating .config for s812
generating .config for s905
generating .config for s905gen2
generating .config for s905gen3
generating .config for s9gen4
generating .config for s922x
generating .config for a3gen2
generating .config for h3
generating .config for h5
generating .config for h6
generating .config for h616
generating .config for riscv
python /build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py /build/package/batocera/emulationstation/batocera-es-system/es_systems.yml /build/package/batocera/emulationstation/batocera-es-system/systems-explanations.yml /build/package/batocera/core/batocera-configgen/configs /tmp/br_systemreport_2906500/configs
Traceback (most recent call last):
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 218, in <module>
    EsSystemConf.generate(args.yml, args.explanationsYaml, args.configsDir, args.defaultsDir)
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 80, in generate
    emulators = EsSystemConf.listEmulators(arch, system, rules[system], explanations, config, defaultEmulator, defaultCore)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/package/batocera/emulationstation/batocera-es-system/batocera-report-system.py", line 182, in listEmulators
    raise Exception("default core ({}/{}) not enabled for {}/{}" . format(defaultEmulator, defaultCore, arch, system))
Exception: default core (libretro/flycast) not enabled for bcm2836/systemsp
+ exit 1
make: *** [Makefile:821: target-post-image] Error 1
make: Leaving directory '/build/buildroot'
make: *** [Makefile:104: h700-build] Error 2
`

**Comment by bladeoner** [comment]
What you can do is use the script in the following PR: https://github.com/knulli-cfw/distribution/pull/98

- After the first build is compiled, use the following command, for example, for the H: ./config_device.sh rg35xx-h
- Then use the following command to compile: make h700-cleanbuild

You can not compile all devices directly after each other. You need to compile them one by one.

**Comment by jbbandos** [comment]
I Still have the same issue at the end, but at least have the "batocera" 1.7GB boot image.
Checking the configs, this seems to be an issue only with the validation tests, as FLYCAST is explicitly disabled for h3 and bcm2836 in config.in:
`	select BR2_PACKAGE_FLYCAST		if !BR2_riscv					&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_BCM2835		&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_BCM2836		&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_BCM2837		&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_RK3326		&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_X86		&& \
						   !BR2_PACKAGE_BATOCERA_TARGET_H3` 

And of course, we're building for h700, not H3 or bcm2836, so no idea why the tests are being done for those two

**Comment by jbbandos** [comment]
@bladeoner 
I ended up editing scripts/linux/systemsReport.sh and changing  line 3 to read `ARCHS="h700"` .
Like that, no other arch is tested, no more spurious errors. There is probably a better way to do this, filling that ARCHS line automatically with the arch you've built...
