### ISSUE TITLE
Knulli freezes when uploading files via SMB

### ISSUE THREAD

**Issue by Akamilad** [knulli-cfw/distribution#86]
### Knulli build version

40-dev-d3b520f949 2024/07/21 02:34

### Your architecture

RG35XX+ and RG35XXH

### Issue description

I experienced an issue regarding files transfer via SMB on Knulli. If I upload a huge amount of files (around 80 Go), until a moment Knulli freezes and I had to hard reboot my device.

### Detailed reproduction steps

I installed Knulli on SD Card 1 with Rufus. 
I plugged an SD2 which I formatted to ext4. 
I changed the storage to external drive. I connected to the SHARE folder via SMB from a W11.
I uploaded 80 Go of PSX games and Knulli totally freezes after transferring around 50 Go/80Go.
I just hard rebooted my device and re-uploaded the missing files.

The same thing happens on a RG35XX+ or RG35XXH with different SD cards.

### Details of any attempts to fix this yourself

I checked with htop if it was linked with a memory leak, but no, the RAM was fine.

### Details of any modifications you have made to Knulli.

None

**Comment by HoroTW** [comment]
Could you try to find out which file caused the interruption? (looking for creation dates)
It would be great if this happened because of a single file or maybe 2-3 in a row and not because of the long transfer itself... 

I also uploaded over 65GB via SMB and had no problem, but I uploaded the files in several passes...
But like you said, if there's no ram leak, I'm not sure why this would happen...

You could try it again and have two ssh connections open to the device and check the logs while the transfer is happening:

First connection:
`tail -f /var/log/samba/log.smbd`.

Second:
`dmesg --follow`.

Maybe that way we can see why it crashes...

**Comment by Akamilad** [comment]
I tried to re experienced the same issue but it seems fine, and nothing in smb logs. I can closed it. (maybe a Windows issue ...)

**Comment by Akamilad** [comment]
I tried to re experienced the same issue but it seems fine, and nothing in smb logs. I can closed it. (maybe a Windows issue ...)
